"use strict";

/**
 * Client runtime for Assessment Pack checks and the end-of-pack summary.
 * Judgement is deterministic. There is no model call and no pathway routing.
 */

function getAssessmentRuntimeScript() {
  return (
    "(function(){" +
    "function q(root,sel){return root.querySelector(sel);}" +
    "function qa(root,sel){return Array.prototype.slice.call(root.querySelectorAll(sel));}" +
    "function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}" +
    "function setResult(item,html,isError){var region=q(item,'[data-assessment-result]');if(!region)return;region.hidden=false;region.className='util-assessment-result'+(isError?' util-assessment-result--prompt':'');region.innerHTML=html;}" +
    "function rationale(item){var text=String(item.getAttribute('data-assessment-rationale')||'').trim();return text?'<p class=\"util-assessment-rationale\">'+escapeHtml(text)+'</p>':'';}" +
    "function notify(item){try{var root=item.closest?item.closest('main.util-learner-renderer-vnext'):null;var target=root||item;var event=null;if(typeof CustomEvent==='function'){event=new CustomEvent('prism:learner-workspace-change',{bubbles:true,detail:{kind:'assessment_selection',workspaceId:item.getAttribute('data-workspace-id')||''}});}else if(document.createEvent){event=document.createEvent('Event');event.initEvent('prism:learner-workspace-change',true,true);}if(event&&target&&target.dispatchEvent)target.dispatchEvent(event);}catch(e){}}" +
    "function mark(item,result){item.setAttribute('data-assessment-checked','true');item.setAttribute('data-assessment-last-result',result);notify(item);}" +
    "function splitList(value){return String(value||'').split('|').map(function(part){return part.trim();}).filter(Boolean);}" +
    "function sameSet(left,right){if(left.length!==right.length)return false;var copy=right.slice();var i;for(i=0;i<left.length;i+=1){var at=copy.indexOf(left[i]);if(at<0)return false;copy.splice(at,1);}return true;}" +
    "function parseMap(value){var out={};splitList(value).forEach(function(pair){var cut=pair.indexOf(':');if(cut<1)return;out[pair.slice(0,cut)]=pair.slice(cut+1);});return out;}" +
    "function checkSingle(item){var selected=q(item,'input[type=radio]:checked');var value=selected?String(selected.value||''):'';if(!value){setResult(item,'<p>Select an answer before checking.</p>',true);item.setAttribute('data-assessment-checked','false');notify(item);return;}var ok=value===String(item.getAttribute('data-assessment-correct')||'');setResult(item,(ok?'<p><strong>Correct.</strong></p>':'<p><strong>Not quite.</strong></p>')+rationale(item),false);mark(item,ok?'correct':'incorrect');}" +
    "function checkMultiple(item){var selected=qa(item,'input[type=checkbox]:checked').map(function(input){return String(input.value||'');});if(!selected.length){setResult(item,'<p>Select at least one answer before checking.</p>',true);return;}var expected=splitList(item.getAttribute('data-assessment-correct-set'));var ok=sameSet(selected,expected);var message='<p><strong>'+(ok?'Correct.':'Not quite.')+'</strong></p>';if(!ok){var missing=expected.filter(function(key){return selected.indexOf(key)<0;});var extra=selected.filter(function(key){return expected.indexOf(key)<0;});if(missing.length&&!extra.length)message+='<p>The selection is incomplete.</p>';else if(extra.length&&!missing.length)message+='<p>The selection includes an option that does not belong.</p>';else message+='<p>The selection is missing a correct option and includes an option that does not belong.</p>';}setResult(item,message+rationale(item),false);mark(item,ok?'correct':'incorrect');}" +
    "function checkOrder(item){var current=qa(item,'[data-assessment-element-id]').map(function(node){return String(node.getAttribute('data-assessment-element-id')||'');});var expected=splitList(item.getAttribute('data-assessment-correct-order'));var ok=current.join('|')===expected.join('|');setResult(item,(ok?'<p><strong>Correct.</strong></p>':'<p><strong>Not quite.</strong> That order is not the one this question asks for.</p>')+rationale(item),false);mark(item,ok?'correct':'incorrect');}" +
    "function checkMap(item,selector,emptyMessage){var expected=parseMap(item.getAttribute('data-assessment-correct-map'));var nodes=qa(item,selector);if(!nodes.length){setResult(item,'<p>'+emptyMessage+'</p>',true);return;}var missing=false;var wrong=false;nodes.forEach(function(node){var subject=String(node.getAttribute('data-assessment-subject')||'');var value=String(node.value||'');if(!value)missing=true;else if(expected[subject]!==value)wrong=true;});if(missing){setResult(item,'<p>'+emptyMessage+'</p>',true);return;}var ok=!wrong;setResult(item,(ok?'<p><strong>Correct.</strong></p>':'<p><strong>Not quite.</strong></p>')+rationale(item),false);mark(item,ok?'correct':'incorrect');}" +
    "function checkItem(item){var form=String(item.getAttribute('data-assessment-form')||'single_answer_mcq');if(form==='multiple_answer_mcq')return checkMultiple(item);if(form==='ordering')return checkOrder(item);if(form==='classification')return checkMap(item,'select[data-assessment-assignment]','Choose a category for each item before checking.');if(form==='matching')return checkMap(item,'select[data-assessment-pair]','Choose a match for each item before checking.');return checkSingle(item);}" +
    "function refreshOrder(list){if(!list)return;var rows=qa(list,'li');rows.forEach(function(li,index){var pos=q(li,'[data-assessment-position]');if(pos)pos.textContent=String(index+1);var up=q(li,'[data-assessment-move=up]');var down=q(li,'[data-assessment-move=down]');if(up)up.disabled=index===0;if(down)down.disabled=index===rows.length-1;});}" +
    "function moveElement(button){var li=button.closest?button.closest('li'):null;if(!li||!li.parentNode)return;var direction=button.getAttribute('data-assessment-move');if(direction==='up'&&li.previousElementSibling&&!button.disabled)li.parentNode.insertBefore(li,li.previousElementSibling);if(direction==='down'&&li.nextElementSibling&&!button.disabled)li.parentNode.insertBefore(li.nextElementSibling,li);refreshOrder(li.parentNode);}" +
    "function evidenceWords(successful,checked){if(checked<=1)return 'Limited evidence: '+checked+' checked component'+(checked===1?'':'.')+'.';if(successful===checked)return 'Consistently successful evidence across '+checked+' checked components.';if(successful===0)return 'These checked components did not yet provide successful evidence for this outcome.';return 'Mixed evidence across '+checked+' checked components.';}" +
    "function evidenceBar(label,successful,checked){var pct=checked?Math.round(100*successful/checked):0;var words=evidenceWords(successful,checked);var count=successful+' of '+checked+' successful';return '<div class=\"util-evidence-row\"><p class=\"util-evidence-statement\">'+escapeHtml(label)+'</p><div class=\"util-evidence-bar\" role=\"img\" aria-label=\"'+escapeHtml(count+' '+words)+'\"><span style=\"width:'+pct+'%\"></span></div><p class=\"util-evidence-count\">'+escapeHtml(count)+'</p><p class=\"util-evidence-note\">'+escapeHtml(words)+'</p></div>';}" +
    "function finishAssessment(section){qa(section,'.util-assessment-item--interactive').forEach(function(item){var form=String(item.getAttribute('data-assessment-form')||'single_answer_mcq');var ready=true;if(form==='multiple_answer_mcq')ready=qa(item,'input[type=checkbox]:checked').length>0;else if(form==='ordering')ready=true;else if(form==='classification')ready=qa(item,'select[data-assessment-assignment]').every(function(node){return !!node.value;});else if(form==='matching')ready=qa(item,'select[data-assessment-pair]').every(function(node){return !!node.value;});else ready=!!q(item,'input[type=radio]:checked');if(ready)checkItem(item);});summarise(section);var button=q(section,'[data-assessment-finish]');if(button)button.disabled=true;}" +
    "function summarise(section){var region=q(section,'[data-assessment-summary]');if(!region)return;var index={};try{index=JSON.parse(section.getAttribute('data-assessment-outcome-index')||'{}');}catch(e){index={};}var buckets={};function bucket(id){if(!buckets[id])buckets[id]={correct:0,incorrect:0,named:''};return buckets[id];}var items=qa(section,'.util-assessment-item--interactive');var unchecked=0;var unnamed=0;items.forEach(function(item){var result=String(item.getAttribute('data-assessment-last-result')||'');var ids=splitList(item.getAttribute('data-assessment-outcomes'));if(!result){unchecked+=1;return;}ids.forEach(function(id){var row=bucket(id);var label=String(index[id]||'').trim();if(label&&label!==id)row.named=label;else unnamed+=1;if(result==='correct')row.correct+=1;else row.incorrect+=1;});});var namedRows=[];Object.keys(buckets).forEach(function(id){var row=buckets[id];var checked=row.correct+row.incorrect;if(!row.named||!checked)return;namedRows.push({label:row.named,successful:row.correct,checked:checked});});var intent=String(section.getAttribute('data-assessment-intent')||'formative_check');var html='';if(!namedRows.length){html='<p>Checked responses cannot be named from the learning-outcome statements, so this summary does not distinguish areas.</p>';}else{if(intent==='pretest_diagnostic')html+='<p><strong>Advisory recommendation.</strong> This does not change what you can study, and it does not certify what you know.</p>';namedRows.forEach(function(row){html+=evidenceBar(row.label,row.successful,row.checked);});}region.hidden=false;region.innerHTML=html;}" +
    "document.addEventListener('click',function(event){var move=event.target&&event.target.closest?event.target.closest('[data-assessment-move]'):null;if(move){event.preventDefault();if(!move.disabled)moveElement(move);return;}var finish=event.target&&event.target.closest?event.target.closest('[data-assessment-finish]'):null;if(finish){event.preventDefault();var finished=finish.closest('[data-region=\"assessment\"]');if(finished)finishAssessment(finished);return;}var review=event.target&&event.target.closest?event.target.closest('[data-assessment-review]'):null;if(review){var section=review.closest('[data-region=\"assessment\"]');if(section)summarise(section);return;}var btn=event.target&&event.target.closest?event.target.closest('[data-assessment-check]'):null;if(!btn)return;var item=btn.closest('.util-assessment-item--interactive');if(!item)return;var host=item.closest('[data-region=\"assessment\"]');if(host&&host.getAttribute('data-feedback-timing')==='end_of_pack')return;event.preventDefault();checkItem(item);});" +
    "qa(document,'[data-assessment-order]').forEach(refreshOrder);" +
    "})();"
  );
}

module.exports = {
  getAssessmentRuntimeScript: getAssessmentRuntimeScript
};
